// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gljroyqzqbpvekftkpat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsanJveXF6cWJwdmVrZnRrcGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDk1MjMsImV4cCI6MjA2Mjk4NTUyM30.eM0SUthzy-kbiTAMHL1rGklHg-hQo5vmm49EyIqN5ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);